title: "TokeiLog - Legal & Support"
description: "Official documentation and legal information for TokeiLog time tracking app"
author: "Yohann Pollonghini, Developer"

# Use remote theme for GitHub Pages
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# Site settings
url: ""
baseurl: ""

# Navigation
header_pages:
  - README.md
  - PRIVACY_POLICY.md
  - TERMS_OF_SERVICE.md
  - LICENSE.md
  - CHANGELOG.md
  - APP_STORE_DESCRIPTION.md

# SEO settings
lang: en
google_analytics: # Add your GA tracking ID here if needed

# Show edit links
show_edit_on_github: false